name: Tests

on:
  push:
    branches: master

env:
  CI: true
  NODE_VERSION: 12

jobs:
  test:
    name: Extension Tests
    runs-on: macos-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Setup Node.js ${{ env.NODE_VERSION }}
        uses: actions/setup-node@v1
        with:
          node-version: ${{ env.NODE_VERSION }}

      - run: node --version
      - run: npm --version

      - name: NPM Install
        run: |
          npm ci
          npm ls --depth=0

      - name: Vscode test
        run: npm run test
